# Generated by Rcpp::compileAttributes - do not edit by hand

.grassmann_merge_iterative_cpp <- function(V_list, k_target_global) {
  .Call('_ndx_grassmann_merge_iterative_cpp', PACKAGE = 'ndx', V_list, k_target_global)
}
