# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apply_ar_filter_matrix_cpp <- function(M, ar_coeffs) {
    .Call(`_ndx_apply_ar_filter_matrix_cpp`, M, ar_coeffs)
}

apply_ar_filter_voxelwise_cpp <- function(Y, coeffs) {
    .Call(`_ndx_apply_ar_filter_voxelwise_cpp`, Y, coeffs)
}

grassmann_merge_iterative_cpp <- function(V_list, k_target_global) {
    .Call(`_ndx_grassmann_merge_iterative_cpp`, V_list, k_target_global)
}

