# Generated by Rcpp::compileAttributes - do not edit by hand

.grassmann_merge_iterative_cpp <- function(V_list, k_target_global) {
  .Call('_ndx_grassmann_merge_iterative_cpp', PACKAGE = 'ndx', V_list, k_target_global)
}

apply_ar_filter_matrix_cpp <- function(M, ar_coeffs) {
  .Call('_ndx_apply_ar_filter_matrix_cpp', PACKAGE = 'ndx', M, ar_coeffs)
}

apply_ar_filter_voxelwise_cpp <- function(Y, coeffs) {
  .Call('_ndx_apply_ar_filter_voxelwise_cpp', PACKAGE = 'ndx', Y, coeffs)
}
